name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches:
      - "release/**"
      - "stage"
      - "main"
      
jobs:
  playwright:
    if: ${{ startsWith(github.head_ref, 'release/') || github.head_ref == 'stage' || github.head_ref == ''}}
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.30.0-focal
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet build

      - name: Ensure browsers are installed
        run: |
          apt update
          apt install python3-pip
          pip install playwright
          HTTPS_PROXY=https://192.0.2.1 playwright install --with-deps chromium

      - name: Run your tests
        run: dotnet test ./TestingPlaywright
