name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches:
      - "release/**"
      - "stage"
      - "main"
      
jobs:
  playwright_browser:
    runs-on: ubuntu-latest
    name: "Download playwright browsers"
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.30.0-focal
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet build
      - name: Ensure browsers are installed
        run: pwsh TestingPlaywright/bin/Debug/net7.0/playwright.ps1 install --with-deps
      - name: Archive browser binaries
        uses: actions/upload-artifact@v3
        with:
          name: playwright-browsers
          path: /ms-playwright/chromium-1045/chrome-linux/chrome
          
  playwright:
    if: ${{ startsWith(github.head_ref, 'release/') || github.head_ref == 'stage' || github.head_ref == ''}}
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    needs: playwright_browser
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Make folder
        run: sudo mkdir -p /ms-playwright/chromium-1045/chrome-linux/chrome
        
      - uses: actions/download-artifact@v3
        with:
          name: playwright-browsers
          path: /ms-playwright/chromium-1045/chrome-linux/chrome

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /ms-playwright/chromium-1045/chrome-linux/chrome
        
      - name: Run your tests
        run: dotnet test ./TestingPlaywright
